In [18]:
# Write a function so that the columns of the output matrix are powers of the input
# vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.

# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
# Theophile Vandermonde.

import numpy as np

def vander_func_increase(arr):
       
    res = np.vander(arr, increasing=True)
    
    return res

arr = np.array([1, 2, 3, 4, 5])
print("Vander matrix of the input array in increasing order of powers:\n\n", vander_func_increase(arr),"\n")

def vander_func_dec(arr):
       
    res = np.vander(arr, increasing=False)
    
    return res

arr = np.array([1, 2, 3, 4, 5])
print("Vander matrix of the input array in decreasing order of powers:\n\n", vander_func_dec(arr),"\n")

def vander_func_N(arr, N):
    
    res = np.vander(arr, N)
    
    return res

arr = np.array([1, 2, 3, 4, 5])
print("Vander matrix of the input array in decreasing order of powers and N-columns:\n\n", vander_func_N(arr, 3),"\n")


Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

Vander matrix of the input array in decreasing order of powers and N-columns:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 



In [16]:
# Problem Statement 2:
# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
# the given sequence is defined as follows:
# The moving average sequence has n-k+1 elements as shown below.
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4
# Thus, the moving average sequence has n-k+1=10-4+1=7 values.

import numpy as np

def mov_avg(a,n):
    
    asum = np.cumsum(a,dtype=float)
    asum[n:]-= asum[:-n]
    return asum[n-1:]/n
    
a = a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
np.array(mov_avg(np.array(a),n=3)).round(2) 
    
    

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])